config/routes.rb
# == Route Map
#
#                                Prefix Verb     URI Pattern                                  Controller#Action
#                     new_admin_session GET      /admins/sign_in(.:format)                    admins/sessions#new
#                         admin_session POST     /admins/sign_in(.:format)                    admins/sessions#create
#                 destroy_admin_session DELETE   /admins/sign_out(.:format)                   admins/sessions#destroy
#                    new_admin_password GET      /admins/password/new(.:format)               admins/passwords#new
#                   edit_admin_password GET      /admins/password/edit(.:format)              admins/passwords#edit
#                        admin_password PATCH    /admins/password(.:format)                   admins/passwords#update
#                                       PUT      /admins/password(.:format)                   admins/passwords#update
#                                       POST     /admins/password(.:format)                   admins/passwords#create
#             cancel_admin_registration GET      /admins/cancel(.:format)                     admins/registrations#cancel
#                new_admin_registration GET      /admins/sign_up(.:format)                    admins/registrations#new
#               edit_admin_registration GET      /admins/edit(.:format)                       admins/registrations#edit
#                    admin_registration PATCH    /admins(.:format)                            admins/registrations#update
#                                       PUT      /admins(.:format)                            admins/registrations#update
#                                       DELETE   /admins(.:format)                            admins/registrations#destroy
#                                       POST     /admins(.:format)                            admins/registrations#create
#                new_admin_confirmation GET      /admins/confirmation/new(.:format)           admins/confirmations#new
#                    admin_confirmation GET      /admins/confirmation(.:format)               admins/confirmations#show
#                                       POST     /admins/confirmation(.:format)               admins/confirmations#create
#                      new_admin_unlock GET      /admins/unlock/new(.:format)                 admins/unlocks#new
#                          admin_unlock GET      /admins/unlock(.:format)                     admins/unlocks#show
#                                       POST     /admins/unlock(.:format)                     admins/unlocks#create
#                                admins GET      /admins(.:format)                            admins#index
#                                 admin GET      /admins/:id(.:format)                        admins#show
#                                       DELETE   /admins/:id(.:format)                        admins#destroy
#                      new_user_session GET      /users/sign_in(.:format)                     users/sessions#new
#                          user_session POST     /users/sign_in(.:format)                     users/sessions#create
#                  destroy_user_session DELETE   /users/sign_out(.:format)                    users/sessions#destroy
#      user_facebook_omniauth_authorize GET|POST /users/auth/facebook(.:format)               users/omniauth_callbacks#passthru
#       user_facebook_omniauth_callback GET|POST /users/auth/facebook/callback(.:format)      users/omniauth_callbacks#facebook
# user_google_oauth2_omniauth_authorize GET|POST /users/auth/google_oauth2(.:format)          users/omniauth_callbacks#passthru
#  user_google_oauth2_omniauth_callback GET|POST /users/auth/google_oauth2/callback(.:format) users/omniauth_callbacks#google_oauth2
#                     new_user_password GET      /users/password/new(.:format)                users/passwords#new
#                    edit_user_password GET      /users/password/edit(.:format)               users/passwords#edit
#                         user_password PATCH    /users/password(.:format)                    users/passwords#update
#                                       PUT      /users/password(.:format)                    users/passwords#update
#                                       POST     /users/password(.:format)                    users/passwords#create
#              cancel_user_registration GET      /users/cancel(.:format)                      users/registrations#cancel
#                 new_user_registration GET      /users/sign_up(.:format)                     users/registrations#new
#                edit_user_registration GET      /users/edit(.:format)                        users/registrations#edit
#                     user_registration PATCH    /users(.:format)                             users/registrations#update
#                                       PUT      /users(.:format)                             users/registrations#update
#                                       DELETE   /users(.:format)                             users/registrations#destroy
#                                       POST     /users(.:format)                             users/registrations#create
#                 new_user_confirmation GET      /users/confirmation/new(.:format)            users/confirmations#new
#                     user_confirmation GET      /users/confirmation(.:format)                users/confirmations#show
#                                       POST     /users/confirmation(.:format)                users/confirmations#create
#                       new_user_unlock GET      /users/unlock/new(.:format)                  users/unlocks#new
#                           user_unlock GET      /users/unlock(.:format)                      users/unlocks#show
#                                       POST     /users/unlock(.:format)                      users/unlocks#create
#                                 users GET      /users(.:format)                             users#index
#                                  user GET      /users/:id(.:format)                         users#show
#                                       DELETE   /users/:id(.:format)                         users#destroy
#                          search_users POST     /users/search(.:format)                      users#index
#                                       GET      /users(.:format)                             users#index
#                                       POST     /users(.:format)                             users#create
#                              new_user GET      /users/new(.:format)                         users#new
#                             edit_user GET      /users/:id/edit(.:format)                    users#edit
#                                       GET      /users/:id(.:format)                         users#show
#                                       PATCH    /users/:id(.:format)                         users#update
#                                       PUT      /users/:id(.:format)                         users#update
#                                       DELETE   /users/:id(.:format)                         users#destroy
#                                  root GET      /                                            static_pages#home
#                                 about GET      /about(.:format)                             static_pages#about
#                               contact GET      /contact(.:format)                           static_pages#contact
# 

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # BEGIN: admin section
  devise_for :admins,
             controllers: { registrations: 'admins/registrations',
                            sessions: 'admins/sessions',
                            passwords: 'admins/passwords',
                            confirmations: 'admins/confirmations',
                            unlocks: 'admins/unlocks' }
  resources :admins, only: [:show, :index, :destroy]
  # END: admin section

  # BEGIN: user section
  devise_for :users,
             controllers: { registrations: 'users/registrations',
                            sessions: 'users/sessions',
                            passwords: 'users/passwords',
                            confirmations: 'users/confirmations',
                            unlocks: 'users/unlocks',
                            omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show, :index, :destroy]
  resources :users do
    collection { post :search, to: 'users#index' }
  end
  # END: user section

  # BEGIN: static pages
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  # END: static pages
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Temporary OmniAuth App by Somebody
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Temporary OmniAuth App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <%-# BEGIN: VARIABLE SECTION -%>
        <% if user_signed_in? %>
          <%-# BEGIN: USER SECTION -%>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              User<br>Menu <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Your Profile", user_path(current_user) %></li>
              <li><%= link_to "Edit Settings", edit_user_registration_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
              </li>
            </ul>
          </li>
          <%-# END: USER SECTION -%>
        <% elsif admin_signed_in? %>
          <%-# BEGIN: ADMIN SECTION -%>
          <li><%= link_to "User Index",   users_path %></li>
          <li><%= link_to "Admin Index", admins_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Admin<br>Menu <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Your Profile", admin_path(current_admin) %></li>
              <li><%= link_to "Edit Settings", edit_admin_registration_path(current_admin) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to 'Logout', destroy_admin_session_path, :method=>'delete' %>
              </li>
            </ul>
          </li>
          <%-# END: ADMIN SECTION -%>
        <% else %>
          <%-# BEGIN: GENERAL PUBLIC -%>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <%-# END: GENERAL PUBLIC -%>
        <% end %>
        <%-# END: VARIABLE SECTION -%>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Contact",   contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>